# Generated by Django 3.2.7 on 2021-10-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='category')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pages')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('content', models.TextField(verbose_name='Контент')),
                ('html', models.TextField(verbose_name='HTML страницы')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='clarion.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='base_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isCategory', to='clarion.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarion.category', verbose_name='Родительская категория'),
        ),
    ]
