# Generated by Django 3.2.7 on 2021-10-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarion', '0003_auto_20211006_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='base_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isCategory', to='clarion.page', verbose_name='Страница'),
        ),
    ]
