# Generated by Django 3.2.7 on 2021-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarion', '0006_alter_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML страницы'),
        ),
    ]
