# Generated by Django 3.2.7 on 2021-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarion', '0010_remove_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
