# Generated by Django 3.2.7 on 2021-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarion', '0011_auto_20211011_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_data',
            field=models.TextField(blank=True, null=True, verbose_name='Мета данные'),
        ),
    ]
